version: '3.1'

services:

  wordpress:
    # image: wordpress
    build: ./build-wp
    ports:
      - 30082:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 30083:80
    environment:
      - PMA_ARBITRARY=1


volumes:
  wp:
    driver_opts:
      type: none
      o: bind
      device: ./wp
  db:
    driver_opts:
      type: none
      o: bind
      device: ./db
